name: Flutter Build

on: [pull_request, push]

jobs:
  build-android:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'
      - uses: subosito/flutter-action@v2.21.0
        with:
          channel: 'stable'
      - run: flutter pub get
      #- run: flutter test
      - run: flutter build apk
      - name: Build Web
        run: flutter build web
  build-mac:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v5
    - uses: subosito/flutter-action@v2.21.0
      with:
        channel: 'stable'
    - run: flutter pub get
    - run: flutter build ios --release --no-codesign
