name: Flutter Build

on: [pull_request, push]

jobs:
  build-android:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: microsoft
          java-version: '11.x'
      - uses: subosito/flutter-action@v2.6.1
        with:
          flutter-version: '1.22.4'
      - run: flutter pub get
      #- run: flutter test
      - run: flutter build apk
  build-mac:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-java@v3
      with:
        distribution: microsoft
        java-version: '11.x'
    - uses: subosito/flutter-action@v2.6.1
      with:
        flutter-version: '1.22.4'
    - run: flutter pub get
    #- run: flutter test
    - run: flutter build apk
    - run: flutter build ios --release --no-codesign
